### ISSUE TITLE
Building without nix / add tested-with to cabal?

### ISSUE THREAD

**Issue by jhrcek** [seanhess/hyperbole#33]
Hello,
I'd like to play with the project and its examples. But it doesn't build with ghc 9.6.6 (using current master).
I'm not using nix, just would like to be able to play with it quickly and see what it's capable of.
Could you please add tested-with field to cabal file to make it explicit which ghc versions are supported?
If you use tested-with you can simply generate github actions config using [haskell-ci](https://github.com/haskell-CI/haskell-ci) which I find very useful.

Maybe you just need to restrict dependency versions a bit more?
For reference, the error I'm getting (using cabal 3.12.1.0, ghc 9.6.6):

```
$ cabal update && cabal build
...
[ 7 of 12] Compiling Web.Hyperbole.Effect ( src/Web/Hyperbole/Effect.hs, /home/jhrcek/Devel/github.com/seanhess/hyperbole/dist-newstyle/build/x86_64-linux/ghc-9.6.6/hyperbole-0.4.0/build/Web/Hyperbole/Effect.o, /home/jhrcek/Devel/github.com/seanhess/hyperbole/dist-newstyle/build/x86_64-linux/ghc-9.6.6/hyperbole-0.4.0/build/Web/Hyperbole/Effect.dyn_o )
Installing   autodocodec-yaml-0.4.0.0 (lib)

src/Web/Hyperbole/Effect.hs:212:5: error: [GHC-39999]
    • Could not deduce ‘Show Response’
        arising from a use of ‘throwError’
      from the context: Server :> es
        bound by the type signature for:
                   runHyperbole :: forall (es :: [Effect]).
                                   (Server :> es) =>
                                   Eff (Hyperbole : es) Response -> Eff es Response
        at src/Web/Hyperbole/Effect.hs:(202,1)-(205,20)
      or from: (HasCallStack, Hyperbole :> localEs)
        bound by a type expected by the context:
                   EffectHandler Hyperbole (State HyperState : Error Response : es)
        at src/Web/Hyperbole/Effect.hs:(206,54)-(219,28)
    • In a stmt of a 'do' block: throwError r
      In the expression:
        do s <- gets @HyperState (.session)
           send $ SendResponse s r
           throwError r
      In a \case alternative:
          RespondEarly r
            -> do s <- gets @HyperState (.session)
                  send $ SendResponse s r
                  throwError r
    |
212 |     throwError r

...


[2 of 2] Compiling Test.Syd.Discover ( src/Test/Syd/Discover.hs, dist/build/Test/Syd/Discover.o, dist/build/Test/Syd/Discover.dyn_o )

src/Test/Syd/Discover.hs:24:62: error: [GHC-76037]
    • Not in scope: ‘reldir’
    • In the quasi-quotation: [reldir|.|]
   |
24 |   testDirRelToBaseDir <- if testBaseDir == testDir then pure [reldir|.|] else stripProperPrefix testBaseDir testDir
   |                                                              ^^^^^^^^^^^
Error: [Cabal-7125]
```

**Comment by seanhess** [comment]
Thanks for reporting this! I've been using the main branch as a development branch. The version on hackage works with ghc 9.6.6. https://hackage.haskell.org/package/hyperbole

I'll test the latest master now. Although it's probably time to start using a dev branch :)

**Comment by seanhess** [comment]
Ok, I fixed the show error and switch to skeletest (I swear I have more issues with sydtest that anything). 

The main branch should work on both ghc 9.6.6 and ghc 9.8.2. I also added a `tested-with` field to the cabal file, per your recommendation. 

In addition, I added a [Getting Started With Cabal](https://github.com/seanhess/hyperbole?tab=readme-ov-file#getting-started-with-cabal) section to the README. Take note if following these directions that you'll need to use the example from [Hackage](https://hackage.haskell.org/package/hyperbole). 

LMK if you have any other issues! And feel free to chime in on some of the other design issues that are open if you have time

**Comment by jhrcek** [comment]
Thank you for jumping on it so quickly.
I was unable to get it hyperbole 0.3.6 from hackage work using your steps from readme (getting the same missing Show instance for throwError).

But I was able to make master work (after fixing what seems like jumbled [from](https://github.com/seanhess/hyperbole/blob/c9714b2cd7d9c135dd7d8cc1847ea0df40761555/src/Web/Hyperbole/Route.hs#L72) from Generic).

**Comment by seanhess** [comment]
Great, glad it is working. The jumbled commit should be fixed too: https://github.com/seanhess/hyperbole/blob/main/src/Web/Hyperbole/Route.hs#L72
